spring:
  application:
    name: webhook-kaizen
server:
  port: 8050

url:
  discord:
    webhook: '${DISCORD_WEBHOOK}'

sonar:
  url: '${SONAR_URL}'
  token: '${TOKEN_SONAR}'

#logging.level.discord.MyClient: DEBUG
