spring:
  application:
    name: webhook-kaizen
server:
  port: 8050

url:
  discord:
    webhook: '${DISCORD_WEBHOOK:000}'

sonar:
  url: '${SONAR_URL:000}'
  token: '${TOKEN_SONAR:000}'

#logging.level.discord.MyClient: DEBUG
