spring:
  application:
    name: webhook-kaizen

url:
  discord:
    webhook: 'https://discord.com/api/webhooks/776448287918129183/-pOWy_BGKD7tuGLCKi1jwQsgn8YXI-hQ3hsZbal6SPN9WUs9hfMbjIbKxyY8N60g4LK0'

logging.level.discord.MyClient: DEBUG
